# src/config.py

# Simulation Settings
TIMESTEP_MINUTES = 15
SIMULATION_DAYS = 7

# Asset Specs
NUCLEAR_CAPACITY_MW = 45
NUCLEAR_RAMP_LIMIT_PCT = 0.01  # Can only change 1% per minute

SOLAR_CAPACITY_MW = 100

ELECTROLYZER_CAPACITY_MW = 80
ELECTROLYZER_MIN_LOAD_PCT = 0.10  # Cannot run below 10%
ELECTROLYZER_RAMP_LIMIT_PCT = 0.20 # Faster than nuclear

BATTERY_CAPACITY_MWH = 5
BATTERY_MAX_DISCHARGE_MW = 10